require "user.plugins"
require "user.options"
require "user.keymaps"
require "user.colorscheme"
require "user.telescope"
require "user.gitsigns"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.nvim-tree"
require "user.bufferline"
require "user.tabby"
require "user.scope"
require "user.scrollbar"
require "user.lualine"
require "user.toggleterm"
require "user.project"
require "user.impatient"
require "user.tint"
-- require "user.indentline"
require "user.alpha"
require "user.whichkey"
require "user.autocommands"
require "user.hlslens"
require "user.reticle"
require "user.undotree"
-- require "user.neorg" 
require "user.harpoon"
require "user.formatter"
require "user.cmp"
require "user.lsp"
-- require "user.image"
